Add missing include, instead of a duplicate
src/wayherb.c:61:38: error: use of undeclared identifier 'O_CREAT'
        sem_t *mutex = sem_open("/wayherb", O_CREAT, 0644, 1);
                                            ^